// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"base/app/helloworld/internal/biz"
	"base/app/helloworld/internal/conf"
	"base/app/helloworld/internal/data"
	"base/app/helloworld/internal/server"
	"base/app/helloworld/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go.opentelemetry.io/otel/sdk/trace"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, registry *conf.Registry, tracerProvider *trace.TracerProvider) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(registry)
	userClient := data.NewUserServiceClient(discovery, tracerProvider)
	cmdable := data.NewRedisCmd(confData, logger)
	dataData, cleanup, err := data.NewData(confData, logger, userClient, cmdable)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	helloworldService := service.NewHelloworldService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, helloworldService, logger)
	httpServer := server.NewHTTPServer(confServer, helloworldService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
