trace:
  endpoint: http://127.0.0.1:14268/api/traces
server:
  http:
    addr: 0.0.0.0:8001
    timeout: 10s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 10s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/test?charset=utf8&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 1s
    write_timeout: 2s
