// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.3
// - protoc             v3.21.5
// source: api/helloworld/v1/helloworld.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationHelloworldGetHelloworld = "/api.helloworld.v1.Helloworld/GetHelloworld"

type HelloworldHTTPServer interface {
	GetHelloworld(context.Context, *GetHelloworldRequest) (*GetHelloworldReply, error)
}

func RegisterHelloworldHTTPServer(s *http.Server, srv HelloworldHTTPServer) {
	r := s.Route("/")
	r.GET("/hello", _Helloworld_GetHelloworld0_HTTP_Handler(srv))
}

func _Helloworld_GetHelloworld0_HTTP_Handler(srv HelloworldHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetHelloworldRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHelloworldGetHelloworld)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetHelloworld(ctx, req.(*GetHelloworldRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetHelloworldReply)
		return ctx.Result(200, reply)
	}
}

type HelloworldHTTPClient interface {
	GetHelloworld(ctx context.Context, req *GetHelloworldRequest, opts ...http.CallOption) (rsp *GetHelloworldReply, err error)
}

type HelloworldHTTPClientImpl struct {
	cc *http.Client
}

func NewHelloworldHTTPClient(client *http.Client) HelloworldHTTPClient {
	return &HelloworldHTTPClientImpl{client}
}

func (c *HelloworldHTTPClientImpl) GetHelloworld(ctx context.Context, in *GetHelloworldRequest, opts ...http.CallOption) (*GetHelloworldReply, error) {
	var out GetHelloworldReply
	pattern := "/hello"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHelloworldGetHelloworld))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
